### ISSUE TITLE
problems on IDA Pro Version 6.95.160808 (64-bit)

### ISSUE THREAD

**Issue by vyrus001** [strazzere/golang_loader_assist#1]
golang_loader_assist.py: 'NoneType' object has no attribute 'startEA'
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.95\python\ida_idaapi.py", line 509, in IDAPython_ExecScript
    execfile(script, g)
  File "C:/Program Files (x86)/IDA 6.95/plugins/golang_loader_assist.py", line 330, in <module>
    main()
  File "C:/Program Files (x86)/IDA 6.95/plugins/golang_loader_assist.py", line 315, in main
    func_added = runtime_init()
  File "C:/Program Files (x86)/IDA 6.95/plugins/golang_loader_assist.py", line 248, in runtime_init
    runtime_ms = create_runtime_ms()
  File "C:/Program Files (x86)/IDA 6.95/plugins/golang_loader_assist.py", line 186, in create_runtime_ms
    if idc.MakeNameEx(runtime_ms.startEA, "runtime_morestack", SN_PUBLIC):
AttributeError: 'NoneType' object has no attribute 'startEA'

**Comment by strazzere** [comment]
It would appear it failing to find the "hook" that I used to identify `runtime_morestack` (specifically I'm looking for `word ptr ds:1003h, 0`. This is causing the `get_func` to return a `NoneType` which results in this stack trace. I'll add code to make this be caught and prevent the following code to be reachable.

However, this means it won't actually complete in trying to map out all the functions. Can you provide the binary which you are running this on or at least a hash? I'd like to dig into this further and see if a different type of hook needs to be used.

Thanks for reporting this!

**Comment by vyrus001** [comment]
I can provide the binary for you soon, I don't want to post it tho because it is designed as a template for services in a CTF I am working on, shall i email it to you?

**Comment by strazzere** [comment]
Email works -- strazz _at_ gmail - and that should give me more to test on for the fix.

**Comment by strazzere** [comment]
That would be excellent, strazz at gmail would be best :)

**Comment by strazzere** [comment]
I haven't received any binaries yet - I'll try hunting down a handful of different one ITW though.

Could you clarify if the binaries you're trying to use the loader on are ELF or another format?

**Comment by vyrus001** [comment]
my last email should have contained several binaries for several different OSs, just posting here to verify / check that they were received.

**Comment by futex** [comment]
Hello,

I have a error too on ida 6.9.160222 (64bits), the message is quite different, but maybe the cause is the same.

Screenshoot of the error is here:
![alt tag](http://i63.tinypic.com/11kayas.png)

**Comment by disconnect3d** [comment]
@futex 
Put this after the imports:
```python
ida_segment = idaapi
ida_funcs = idaapi
ida_xref = idaapi
ida_search = idaapi
ida_s = idaapi
```

Or pull the code from PR https://github.com/strazzere/golang_loader_assist/pull/4/files as this actually renames all of above into `idaapi` and so fixes your problem.

**Comment by strazzere** [comment]
Interesting - thank you for the comment and the PR. I will definitely add this to my list of things to relook at. I've actually be refactoring this code a bit so that it will work better with 32bit code, PE and MachO files. Thanks

**Comment by strazzere** [comment]
If you repull from master - this should all be handled. Thanks!
