### ISSUE TITLE
Allow parsing of MachO files

### ISSUE THREAD

**Issue by strazzere** [strazzere/golang_loader_assist#3]
The structure is similar, if not the same, for MachO files - allow parsing of these.

**Comment by demonduck** [comment]
Part of this is addressed in https://github.com/strazzere/golang_loader_assist/pull/5

**Comment by strazzere** [comment]
Need to follow up on this - verify it worked on the bulk of files - then will close.

**Comment by strazzere** [comment]
Ran across a large corpus of MachO binaries (~10k) specifically with ~2k of them being various golang binaries. Didn't see any crazy errors or inconsistencies so I'm going to consider this done.
